"""reserve e-comm

Revision ID: 146e28f19f56
Revises: fd5858197539
Create Date: 2026-05-14 14:04:31.245290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146e28f19f56'
down_revision: Union[str, Sequence[str], None] = 'fd5858197539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_stock", sa.Column("reserve_ecomm_qty", sa.Numeric(), nullable=False, server_default="0",),)
    op.add_column("temp_stock_import", sa.Column("reserve_ecomm_qty", sa.Numeric(), nullable=False, server_default="0",),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_stock_import', 'reserve_ecomm_qty')
    op.drop_column('product_stock', 'reserve_ecomm_qty')
    # ### end Alembic commands ###
