"""create Target price

Revision ID: 385355c9be0b
Revises: 8482d406e241
Create Date: 2026-05-30 17:04:07.190554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385355c9be0b'
down_revision: Union[str, Sequence[str], None] = '8482d406e241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target_price_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calc_date', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('target_supplier_id', sa.Integer(), nullable=False),
    sa.Column('donor_supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('supplier_product_name', sa.String(length=500), nullable=True),
    sa.Column('target_price_l', sa.Numeric(), nullable=False),
    sa.Column('target_price_pack', sa.Numeric(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_used', sa.Numeric(), nullable=False),
    sa.Column('full_cost_msk_source', sa.Numeric(), nullable=False),
    sa.Column('cost_novo_wvat_recalculated', sa.Numeric(), nullable=False),
    sa.Column('fx_markup_used', sa.Numeric(), nullable=False),
    sa.Column('transport_used', sa.Numeric(), nullable=False),
    sa.Column('reexport_used', sa.Numeric(), nullable=False),
    sa.Column('agent_fee_used', sa.Numeric(), nullable=False),
    sa.Column('has_customs_used', sa.Boolean(), nullable=False),
    sa.Column('via_novo_used', sa.Boolean(), nullable=False),
    sa.Column('bank_fee_used', sa.Numeric(), nullable=False),
    sa.Column('customs_fee_used', sa.Numeric(), nullable=False),
    sa.Column('additional_customs_used', sa.Numeric(), nullable=False),
    sa.Column('storage_used', sa.Numeric(), nullable=False),
    sa.Column('move_novo_used', sa.Numeric(), nullable=False),
    sa.Column('move_msk_used', sa.Numeric(), nullable=False),
    sa.Column('marking_used', sa.Numeric(), nullable=False),
    sa.Column('is_excise_used', sa.Boolean(), nullable=False),
    sa.Column('vat_used', sa.Numeric(), nullable=False),
    sa.Column('money_used', sa.Numeric(), nullable=False),
    sa.Column('price_date_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['donor_supplier_id'], ['suppliers.id'], name=op.f('fk_target_price_calculations_donor_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_target_price_calculations_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_supplier_id'], ['suppliers.id'], name=op.f('fk_target_price_calculations_target_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_target_price_calculations'))
    )
    op.create_index('ix_target_price_calc_batch_user', 'target_price_calculations', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_target_price_calculations_batch_id'), 'target_price_calculations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_target_price_calculations_donor_supplier_id'), 'target_price_calculations', ['donor_supplier_id'], unique=False)
    op.create_index(op.f('ix_target_price_calculations_imported_by'), 'target_price_calculations', ['imported_by'], unique=False)
    op.create_index(op.f('ix_target_price_calculations_product_id'), 'target_price_calculations', ['product_id'], unique=False)
    op.create_index(op.f('ix_target_price_calculations_target_supplier_id'), 'target_price_calculations', ['target_supplier_id'], unique=False)
    op.create_table('temp_target_price_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('target_supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_target_price_import_selected_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_supplier_id'], ['suppliers.id'], name=op.f('fk_temp_target_price_import_target_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_target_price_import'))
    )
    op.create_index('ix_temp_target_price_batch_user', 'temp_target_price_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_target_price_import_batch_id'), 'temp_target_price_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_target_price_import_imported_by'), 'temp_target_price_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_target_price_import_selected_product_id'), 'temp_target_price_import', ['selected_product_id'], unique=False)
    op.create_index(op.f('ix_temp_target_price_import_target_supplier_id'), 'temp_target_price_import', ['target_supplier_id'], unique=False)
    op.create_table('temp_target_price_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temp_import_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('calc_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('supplier_product_name', sa.String(length=500), nullable=True),
    sa.Column('supplier_price', sa.Numeric(), nullable=False),
    sa.Column('price_date_used', sa.DateTime(), nullable=True),
    sa.Column('cost_novo_wvat', sa.Numeric(), nullable=False),
    sa.Column('full_cost_msk', sa.Numeric(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_used', sa.Numeric(), nullable=False),
    sa.Column('fx_markup_used', sa.Numeric(), nullable=False),
    sa.Column('transport_used', sa.Numeric(), nullable=False),
    sa.Column('reexport_used', sa.Numeric(), nullable=False),
    sa.Column('agent_fee_used', sa.Numeric(), nullable=False),
    sa.Column('has_customs_used', sa.Boolean(), nullable=False),
    sa.Column('via_novo_used', sa.Boolean(), nullable=False),
    sa.Column('bank_fee_used', sa.Numeric(), nullable=False),
    sa.Column('customs_fee_used', sa.Numeric(), nullable=False),
    sa.Column('move_novo_used', sa.Numeric(), nullable=False),
    sa.Column('move_msk_used', sa.Numeric(), nullable=False),
    sa.Column('is_excise_used', sa.Boolean(), nullable=False),
    sa.Column('additional_customs_used', sa.Numeric(), nullable=False),
    sa.Column('storage_used', sa.Numeric(), nullable=False),
    sa.Column('marking_used', sa.Numeric(), nullable=False),
    sa.Column('opt_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_temp_target_price_options_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_temp_target_price_options_supplier_id_suppliers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['temp_import_id'], ['temp_target_price_import.id'], name=op.f('fk_temp_target_price_options_temp_import_id_temp_target_price_import'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_target_price_options'))
    )
    op.create_index(op.f('ix_temp_target_price_options_batch_id'), 'temp_target_price_options', ['batch_id'], unique=False)
    op.create_index('ix_temp_target_price_options_batch_user', 'temp_target_price_options', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_target_price_options_imported_by'), 'temp_target_price_options', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_target_price_options_product_id'), 'temp_target_price_options', ['product_id'], unique=False)
    op.create_index(op.f('ix_temp_target_price_options_supplier_id'), 'temp_target_price_options', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_temp_target_price_options_temp_import_id'), 'temp_target_price_options', ['temp_import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_target_price_options_temp_import_id'), table_name='temp_target_price_options')
    op.drop_index(op.f('ix_temp_target_price_options_supplier_id'), table_name='temp_target_price_options')
    op.drop_index(op.f('ix_temp_target_price_options_product_id'), table_name='temp_target_price_options')
    op.drop_index(op.f('ix_temp_target_price_options_imported_by'), table_name='temp_target_price_options')
    op.drop_index('ix_temp_target_price_options_batch_user', table_name='temp_target_price_options')
    op.drop_index(op.f('ix_temp_target_price_options_batch_id'), table_name='temp_target_price_options')
    op.drop_table('temp_target_price_options')
    op.drop_index(op.f('ix_temp_target_price_import_target_supplier_id'), table_name='temp_target_price_import')
    op.drop_index(op.f('ix_temp_target_price_import_selected_product_id'), table_name='temp_target_price_import')
    op.drop_index(op.f('ix_temp_target_price_import_imported_by'), table_name='temp_target_price_import')
    op.drop_index(op.f('ix_temp_target_price_import_batch_id'), table_name='temp_target_price_import')
    op.drop_index('ix_temp_target_price_batch_user', table_name='temp_target_price_import')
    op.drop_table('temp_target_price_import')
    op.drop_index(op.f('ix_target_price_calculations_target_supplier_id'), table_name='target_price_calculations')
    op.drop_index(op.f('ix_target_price_calculations_product_id'), table_name='target_price_calculations')
    op.drop_index(op.f('ix_target_price_calculations_imported_by'), table_name='target_price_calculations')
    op.drop_index(op.f('ix_target_price_calculations_donor_supplier_id'), table_name='target_price_calculations')
    op.drop_index(op.f('ix_target_price_calculations_batch_id'), table_name='target_price_calculations')
    op.drop_index('ix_target_price_calc_batch_user', table_name='target_price_calculations')
    op.drop_table('target_price_calculations')
    # ### end Alembic commands ###
