"""changed TempSupplierOrdersImport

Revision ID: 435b82aad518
Revises: c55fa7568ce9
Create Date: 2026-04-18 03:47:50.028646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435b82aad518'
down_revision: Union[str, Sequence[str], None] = 'c55fa7568ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_supplier_orders_import', 'transit_qty')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_supplier_orders_import', sa.Column('transit_qty', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
