"""Target price chaged

Revision ID: 4cd8dc16d116
Revises: 9ce0061bdaef
Create Date: 2026-06-01 14:33:40.459259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd8dc16d116'
down_revision: Union[str, Sequence[str], None] = '9ce0061bdaef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('target_price_calculations', sa.Column('donor_supplier_price', sa.Numeric(), nullable=True))
    op.add_column('target_price_calculations', sa.Column('donor_currency_code', sa.String(length=10), nullable=True))
    op.add_column('target_price_calculations', sa.Column('donor_fx_rate_used', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('target_price_calculations', 'donor_fx_rate_used')
    op.drop_column('target_price_calculations', 'donor_currency_code')
    op.drop_column('target_price_calculations', 'donor_supplier_price')
    # ### end Alembic commands ###
