"""change to cascade

Revision ID: 643b0dccea1c
Revises: dac7ce3d480a
Create Date: 2026-04-16 21:24:48.954813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643b0dccea1c'
down_revision: Union[str, Sequence[str], None] = 'dac7ce3d480a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_current_supplier_prices_supplier_id_suppliers'), 'current_supplier_prices', type_='foreignkey')
    op.drop_constraint(op.f('fk_current_supplier_prices_product_id_products'), 'current_supplier_prices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_current_supplier_prices_product_id_products'), 'current_supplier_prices', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_current_supplier_prices_supplier_id_suppliers'), 'current_supplier_prices', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_customer_price_calc_batch_user', 'customer_price_calculations', ['batch_id', 'imported_by'], unique=False)
    op.drop_constraint(op.f('fk_customer_price_calculations_supplier_id_suppliers'), 'customer_price_calculations', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_price_calculations_product_id_products'), 'customer_price_calculations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_price_calculations_product_id_products'), 'customer_price_calculations', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_customer_price_calculations_supplier_id_suppliers'), 'customer_price_calculations', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_price_history_product_id_products'), 'price_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_price_history_supplier_id_suppliers'), 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_price_history_supplier_id_suppliers'), 'price_history', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_price_history_product_id_products'), 'price_history', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_product_articles_product_id_products'), 'product_articles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_articles_product_id_products'), 'product_articles', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_product_stock_product_id_products'), 'product_stock', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_stock_product_id_products'), 'product_stock', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_supplier_price_calculations_supplier_id_suppliers'), 'supplier_price_calculations', type_='foreignkey')
    op.drop_constraint(op.f('fk_supplier_price_calculations_product_id_products'), 'supplier_price_calculations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplier_price_calculations_product_id_products'), 'supplier_price_calculations', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_supplier_price_calculations_supplier_id_suppliers'), 'supplier_price_calculations', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_customer_cost_import_selected_product_id_products'), 'temp_customer_cost_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_customer_cost_import_selected_product_id_products'), 'temp_customer_cost_import', 'products', ['selected_product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_customer_cost_options_supplier_id_suppliers'), 'temp_customer_cost_options', type_='foreignkey')
    op.drop_constraint(op.f('fk_temp_customer_cost_options_product_id_products'), 'temp_customer_cost_options', type_='foreignkey')
    op.drop_constraint(op.f('fk_temp_customer_cost_options_temp_import_id_temp_custo_d523'), 'temp_customer_cost_options', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_customer_cost_options_temp_import_id_temp_customer_cost_import'), 'temp_customer_cost_options', 'temp_customer_cost_import', ['temp_import_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_temp_customer_cost_options_supplier_id_suppliers'), 'temp_customer_cost_options', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_temp_customer_cost_options_product_id_products'), 'temp_customer_cost_options', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_is_import_selected_product_id_products'), 'temp_is_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_is_import_selected_product_id_products'), 'temp_is_import', 'products', ['selected_product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_price_import_selected_product_id_products'), 'temp_price_import', type_='foreignkey')
    op.drop_constraint(op.f('fk_temp_price_import_supplier_id_suppliers'), 'temp_price_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_price_import_supplier_id_suppliers'), 'temp_price_import', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_temp_price_import_selected_product_id_products'), 'temp_price_import', 'products', ['selected_product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_product_search_import_selected_product_id_products'), 'temp_product_search_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_product_search_import_selected_product_id_products'), 'temp_product_search_import', 'products', ['selected_product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_stock_import_selected_product_id_products'), 'temp_stock_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_stock_import_selected_product_id_products'), 'temp_stock_import', 'products', ['selected_product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_temp_supplier_orders_import_selected_product_id_products'), 'temp_supplier_orders_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_supplier_orders_import_selected_product_id_products'), 'temp_supplier_orders_import', 'products', ['selected_product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_temp_supplier_orders_import_selected_product_id_products'), 'temp_supplier_orders_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_supplier_orders_import_selected_product_id_products'), 'temp_supplier_orders_import', 'products', ['selected_product_id'], ['id'])
    op.drop_constraint(op.f('fk_temp_stock_import_selected_product_id_products'), 'temp_stock_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_stock_import_selected_product_id_products'), 'temp_stock_import', 'products', ['selected_product_id'], ['id'])
    op.drop_constraint(op.f('fk_temp_product_search_import_selected_product_id_products'), 'temp_product_search_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_product_search_import_selected_product_id_products'), 'temp_product_search_import', 'products', ['selected_product_id'], ['id'])
    op.drop_constraint(op.f('fk_temp_price_import_selected_product_id_products'), 'temp_price_import', type_='foreignkey')
    op.drop_constraint(op.f('fk_temp_price_import_supplier_id_suppliers'), 'temp_price_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_price_import_supplier_id_suppliers'), 'temp_price_import', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(op.f('fk_temp_price_import_selected_product_id_products'), 'temp_price_import', 'products', ['selected_product_id'], ['id'])
    op.drop_constraint(op.f('fk_temp_is_import_selected_product_id_products'), 'temp_is_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_is_import_selected_product_id_products'), 'temp_is_import', 'products', ['selected_product_id'], ['id'])
    op.drop_constraint(op.f('fk_temp_customer_cost_options_product_id_products'), 'temp_customer_cost_options', type_='foreignkey')
    op.drop_constraint(op.f('fk_temp_customer_cost_options_supplier_id_suppliers'), 'temp_customer_cost_options', type_='foreignkey')
    op.drop_constraint(op.f('fk_temp_customer_cost_options_temp_import_id_temp_customer_cost_import'), 'temp_customer_cost_options', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_customer_cost_options_temp_import_id_temp_custo_d523'), 'temp_customer_cost_options', 'temp_customer_cost_import', ['temp_import_id'], ['id'])
    op.create_foreign_key(op.f('fk_temp_customer_cost_options_product_id_products'), 'temp_customer_cost_options', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('fk_temp_customer_cost_options_supplier_id_suppliers'), 'temp_customer_cost_options', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(op.f('fk_temp_customer_cost_import_selected_product_id_products'), 'temp_customer_cost_import', type_='foreignkey')
    op.create_foreign_key(op.f('fk_temp_customer_cost_import_selected_product_id_products'), 'temp_customer_cost_import', 'products', ['selected_product_id'], ['id'])
    op.drop_constraint(op.f('fk_supplier_price_calculations_supplier_id_suppliers'), 'supplier_price_calculations', type_='foreignkey')
    op.drop_constraint(op.f('fk_supplier_price_calculations_product_id_products'), 'supplier_price_calculations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_supplier_price_calculations_product_id_products'), 'supplier_price_calculations', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('fk_supplier_price_calculations_supplier_id_suppliers'), 'supplier_price_calculations', 'suppliers', ['supplier_id'], ['id'])
    op.drop_constraint(op.f('fk_product_stock_product_id_products'), 'product_stock', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_stock_product_id_products'), 'product_stock', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('fk_product_articles_product_id_products'), 'product_articles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_product_articles_product_id_products'), 'product_articles', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('fk_price_history_product_id_products'), 'price_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_price_history_supplier_id_suppliers'), 'price_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_price_history_supplier_id_suppliers'), 'price_history', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(op.f('fk_price_history_product_id_products'), 'price_history', 'products', ['product_id'], ['id'])
    op.drop_constraint(op.f('fk_customer_price_calculations_supplier_id_suppliers'), 'customer_price_calculations', type_='foreignkey')
    op.drop_constraint(op.f('fk_customer_price_calculations_product_id_products'), 'customer_price_calculations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_price_calculations_product_id_products'), 'customer_price_calculations', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('fk_customer_price_calculations_supplier_id_suppliers'), 'customer_price_calculations', 'suppliers', ['supplier_id'], ['id'])
    op.drop_index('ix_customer_price_calc_batch_user', table_name='customer_price_calculations')
    op.drop_constraint(op.f('fk_current_supplier_prices_supplier_id_suppliers'), 'current_supplier_prices', type_='foreignkey')
    op.drop_constraint(op.f('fk_current_supplier_prices_product_id_products'), 'current_supplier_prices', type_='foreignkey')
    op.create_foreign_key(op.f('fk_current_supplier_prices_product_id_products'), 'current_supplier_prices', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('fk_current_supplier_prices_supplier_id_suppliers'), 'current_supplier_prices', 'suppliers', ['supplier_id'], ['id'])
    # ### end Alembic commands ###
