"""changed CustomerPriceCalculation

Revision ID: 8482d406e241
Revises: 146e28f19f56
Create Date: 2026-05-27 10:51:38.086373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8482d406e241'
down_revision: Union[str, Sequence[str], None] = '146e28f19f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_price_calculations', sa.Column('customer_product_name', sa.String(length=500), nullable=True))
    op.drop_column('customer_price_calculations', 'supplier_product_name')
    op.add_column('temp_customer_cost_options', sa.Column('customer_product_name', sa.String(length=500), nullable=True))
    op.drop_column('temp_customer_cost_options', 'supplier_product_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temp_customer_cost_options', sa.Column('supplier_product_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('temp_customer_cost_options', 'customer_product_name')
    op.add_column('customer_price_calculations', sa.Column('supplier_product_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('customer_price_calculations', 'customer_product_name')
    # ### end Alembic commands ###
