"""changed SupplierPriceCalculation

Revision ID: baba43d952a4
Revises: 480d67e594cc
Create Date: 2026-04-17 20:13:55.366628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baba43d952a4'
down_revision: Union[str, Sequence[str], None] = '480d67e594cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_price_calculations', sa.Column('import_row_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_price_calculations', 'import_row_no')
    # ### end Alembic commands ###
