"""initial schema

Revision ID: d11ac03f568f
Revises: 
Create Date: 2026-04-14 01:10:44.509362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11ac03f568f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('rate_to_rub', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('currency_code', name=op.f('pk_exchange_rates'))
    )
    op.create_table('fixed_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customs_clearance', sa.Numeric(), nullable=False),
    sa.Column('additional_customs', sa.Numeric(), nullable=False),
    sa.Column('excise', sa.Numeric(), nullable=False),
    sa.Column('eco_fee', sa.Numeric(), nullable=False),
    sa.Column('vat', sa.Numeric(), nullable=False),
    sa.Column('customs_fee', sa.Numeric(), nullable=False),
    sa.Column('bank_fee', sa.Numeric(), nullable=False),
    sa.Column('money', sa.Numeric(), nullable=False),
    sa.Column('storage', sa.Numeric(), nullable=False),
    sa.Column('move_novo_tamozh', sa.Numeric(), nullable=False),
    sa.Column('move_tamozh_chekhov', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fixed_costs'))
    )
    op.create_table('marking_rates',
    sa.Column('pack_type', sa.String(length=100), nullable=False),
    sa.Column('cost_per_l', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('pack_type', name=op.f('pk_marking_rates'))
    )
    op.create_table('pack_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pack_types'))
    )
    op.create_index(op.f('ix_pack_types_name'), 'pack_types', ['name'], unique=False)
    op.create_index(op.f('ix_pack_types_volume'), 'pack_types', ['volume'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('family', sa.String(length=500), nullable=True),
    sa.Column('pack', sa.Numeric(), nullable=False),
    sa.Column('is_excise', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_family'), 'products', ['family'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('transport_cost_per_l', sa.Numeric(), nullable=False),
    sa.Column('reexport_percent', sa.Numeric(), nullable=False),
    sa.Column('fx_rate_markup', sa.Numeric(), nullable=False),
    sa.Column('is_via_novo', sa.Boolean(), nullable=False),
    sa.Column('has_import_duty', sa.Boolean(), nullable=False),
    sa.Column('rating_calc', sa.Boolean(), nullable=False),
    sa.Column('marks_for_us', sa.Boolean(), nullable=False),
    sa.Column('is_rf', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=True)
    op.create_table('current_supplier_prices',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_current_supplier_prices_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_current_supplier_prices_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id', name=op.f('pk_current_supplier_prices'))
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_history_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_price_history_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_history'))
    )
    op.create_index(op.f('ix_price_history_price_date'), 'price_history', ['price_date'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_history_supplier_id'), 'price_history', ['supplier_id'], unique=False)
    op.create_table('product_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_articles_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_articles')),
    sa.UniqueConstraint('product_id', 'article', 'name', name='uq_prod_articles_main')
    )
    op.create_index('ix_prod_articles_article_name', 'product_articles', ['article', 'name'], unique=False)
    op.create_index(op.f('ix_product_articles_article'), 'product_articles', ['article'], unique=False)
    op.create_index(op.f('ix_product_articles_name'), 'product_articles', ['name'], unique=False)
    op.create_index(op.f('ix_product_articles_product_id'), 'product_articles', ['product_id'], unique=False)
    op.create_table('product_stock',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('stock_update_date', sa.DateTime(), nullable=True),
    sa.Column('supplier_orders_update_date', sa.DateTime(), nullable=True),
    sa.Column('is_update_date', sa.DateTime(), nullable=True),
    sa.Column('stock_qty', sa.Numeric(), nullable=False),
    sa.Column('markdown_qty', sa.Numeric(), nullable=False),
    sa.Column('reserve_qty', sa.Numeric(), nullable=False),
    sa.Column('lpc', sa.Numeric(), nullable=False),
    sa.Column('landed_cost', sa.Numeric(), nullable=False),
    sa.Column('distr_price', sa.Numeric(), nullable=False),
    sa.Column('promo_price', sa.Numeric(), nullable=False),
    sa.Column('transit_qty', sa.Numeric(), nullable=False),
    sa.Column('order_qty', sa.Numeric(), nullable=False),
    sa.Column('is_order_qty', sa.Numeric(), nullable=False),
    sa.Column('is_confirmed_order_qty', sa.Numeric(), nullable=False),
    sa.Column('is_stock_qty', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_stock_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', name=op.f('pk_product_stock'))
    )
    op.create_table('supplier_price_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calc_date', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('supplier_product_name', sa.String(length=500), nullable=True),
    sa.Column('supplier_price', sa.Numeric(), nullable=False),
    sa.Column('cost_novo_wvat', sa.Numeric(), nullable=False),
    sa.Column('full_cost_msk', sa.Numeric(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_used', sa.Numeric(), nullable=False),
    sa.Column('fx_markup_used', sa.Numeric(), nullable=False),
    sa.Column('transport_used', sa.Numeric(), nullable=False),
    sa.Column('reexport_used', sa.Numeric(), nullable=False),
    sa.Column('has_customs_used', sa.Boolean(), nullable=False),
    sa.Column('via_novo_used', sa.Boolean(), nullable=False),
    sa.Column('bank_fee_used', sa.Numeric(), nullable=False),
    sa.Column('customs_fee_used', sa.Numeric(), nullable=False),
    sa.Column('move_novo_used', sa.Numeric(), nullable=False),
    sa.Column('move_msk_used', sa.Numeric(), nullable=False),
    sa.Column('is_excise_used', sa.Boolean(), nullable=False),
    sa.Column('additional_customs_used', sa.Numeric(), nullable=False),
    sa.Column('storage_used', sa.Numeric(), nullable=False),
    sa.Column('marking_used', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_price_calculations_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_price_calculations_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_price_calculations'))
    )
    op.create_index(op.f('ix_supplier_price_calculations_batch_id'), 'supplier_price_calculations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_supplier_price_calculations_imported_by'), 'supplier_price_calculations', ['imported_by'], unique=False)
    op.create_index(op.f('ix_supplier_price_calculations_product_id'), 'supplier_price_calculations', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_price_calculations_supplier_id'), 'supplier_price_calculations', ['supplier_id'], unique=False)
    op.create_table('temp_customer_cost_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('pack', sa.Numeric(), nullable=True),
    sa.Column('qty_pcs', sa.Numeric(), nullable=True),
    sa.Column('volume_l', sa.Numeric(), nullable=True),
    sa.Column('purchase_type', sa.String(length=255), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_customer_cost_import_selected_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_customer_cost_import'))
    )
    op.create_index('ix_temp_cc_import_batch_user', 'temp_customer_cost_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_import_batch_id'), 'temp_customer_cost_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_import_imported_by'), 'temp_customer_cost_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_import_selected_product_id'), 'temp_customer_cost_import', ['selected_product_id'], unique=False)
    op.create_table('temp_is_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('source_article', sa.String(length=255), nullable=True),
    sa.Column('source_product_name', sa.String(length=500), nullable=True),
    sa.Column('confirmed_qty', sa.Numeric(), nullable=False),
    sa.Column('remains_qty', sa.Numeric(), nullable=False),
    sa.Column('stock_qty', sa.Numeric(), nullable=False),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_is_import_selected_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_is_import'))
    )
    op.create_index('ix_temp_is_batch_user', 'temp_is_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_is_import_batch_id'), 'temp_is_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_is_import_imported_by'), 'temp_is_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_is_import_selected_product_id'), 'temp_is_import', ['selected_product_id'], unique=False)
    op.create_table('temp_price_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('price_pack', sa.Numeric(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_price_import_selected_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_temp_price_import_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_price_import'))
    )
    op.create_index('ix_temp_price_batch_user', 'temp_price_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_price_import_batch_id'), 'temp_price_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_price_import_imported_by'), 'temp_price_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_price_import_selected_product_id'), 'temp_price_import', ['selected_product_id'], unique=False)
    op.create_index(op.f('ix_temp_price_import_supplier_id'), 'temp_price_import', ['supplier_id'], unique=False)
    op.create_table('temp_stock_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('source_article', sa.String(length=255), nullable=True),
    sa.Column('source_sku', sa.String(length=255), nullable=True),
    sa.Column('source_product_name', sa.String(length=500), nullable=True),
    sa.Column('source_origin', sa.String(length=255), nullable=True),
    sa.Column('source_brand_group', sa.String(length=255), nullable=True),
    sa.Column('lpc', sa.Numeric(), nullable=True),
    sa.Column('landed_cost', sa.Numeric(), nullable=True),
    sa.Column('distr_price', sa.Numeric(), nullable=True),
    sa.Column('promo_price', sa.Numeric(), nullable=True),
    sa.Column('stock_qty', sa.Numeric(), nullable=False),
    sa.Column('markdown_qty', sa.Numeric(), nullable=False),
    sa.Column('reserve_qty', sa.Numeric(), nullable=False),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('has_lpc_warning', sa.Boolean(), nullable=False),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_stock_import_selected_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_stock_import'))
    )
    op.create_index('ix_temp_stock_batch_user', 'temp_stock_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_stock_import_batch_id'), 'temp_stock_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_stock_import_imported_by'), 'temp_stock_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_stock_import_selected_product_id'), 'temp_stock_import', ['selected_product_id'], unique=False)
    op.create_table('temp_supplier_orders_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('source_article', sa.String(length=255), nullable=True),
    sa.Column('source_product_name', sa.String(length=500), nullable=True),
    sa.Column('transit_qty', sa.Numeric(), nullable=False),
    sa.Column('order_qty', sa.Numeric(), nullable=False),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_supplier_orders_import_selected_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_supplier_orders_import'))
    )
    op.create_index('ix_temp_so_batch_user', 'temp_supplier_orders_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_supplier_orders_import_batch_id'), 'temp_supplier_orders_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_supplier_orders_import_imported_by'), 'temp_supplier_orders_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_supplier_orders_import_selected_product_id'), 'temp_supplier_orders_import', ['selected_product_id'], unique=False)
    op.create_table('temp_customer_cost_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temp_import_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('calc_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('supplier_article', sa.String(length=255), nullable=True),
    sa.Column('supplier_product_name', sa.String(length=500), nullable=True),
    sa.Column('supplier_price', sa.Numeric(), nullable=False),
    sa.Column('price_date_used', sa.DateTime(), nullable=True),
    sa.Column('cost_novo_wvat', sa.Numeric(), nullable=False),
    sa.Column('full_cost_msk', sa.Numeric(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('fx_rate_used', sa.Numeric(), nullable=False),
    sa.Column('fx_markup_used', sa.Numeric(), nullable=False),
    sa.Column('transport_used', sa.Numeric(), nullable=False),
    sa.Column('reexport_used', sa.Numeric(), nullable=False),
    sa.Column('has_customs_used', sa.Boolean(), nullable=False),
    sa.Column('via_novo_used', sa.Boolean(), nullable=False),
    sa.Column('bank_fee_used', sa.Numeric(), nullable=False),
    sa.Column('customs_fee_used', sa.Numeric(), nullable=False),
    sa.Column('move_novo_used', sa.Numeric(), nullable=False),
    sa.Column('move_msk_used', sa.Numeric(), nullable=False),
    sa.Column('is_excise_used', sa.Boolean(), nullable=False),
    sa.Column('additional_customs_used', sa.Numeric(), nullable=False),
    sa.Column('storage_used', sa.Numeric(), nullable=False),
    sa.Column('marking_used', sa.Numeric(), nullable=False),
    sa.Column('opt_rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_temp_customer_cost_options_product_id_products')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_temp_customer_cost_options_supplier_id_suppliers')),
    sa.ForeignKeyConstraint(['temp_import_id'], ['temp_customer_cost_import.id'], name=op.f('fk_temp_customer_cost_options_temp_import_id_temp_customer_cost_import')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_customer_cost_options'))
    )
    op.create_index('ix_temp_cc_options_batch_user', 'temp_customer_cost_options', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_options_batch_id'), 'temp_customer_cost_options', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_options_imported_by'), 'temp_customer_cost_options', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_options_product_id'), 'temp_customer_cost_options', ['product_id'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_options_supplier_id'), 'temp_customer_cost_options', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_temp_customer_cost_options_temp_import_id'), 'temp_customer_cost_options', ['temp_import_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_customer_cost_options_temp_import_id'), table_name='temp_customer_cost_options')
    op.drop_index(op.f('ix_temp_customer_cost_options_supplier_id'), table_name='temp_customer_cost_options')
    op.drop_index(op.f('ix_temp_customer_cost_options_product_id'), table_name='temp_customer_cost_options')
    op.drop_index(op.f('ix_temp_customer_cost_options_imported_by'), table_name='temp_customer_cost_options')
    op.drop_index(op.f('ix_temp_customer_cost_options_batch_id'), table_name='temp_customer_cost_options')
    op.drop_index('ix_temp_cc_options_batch_user', table_name='temp_customer_cost_options')
    op.drop_table('temp_customer_cost_options')
    op.drop_index(op.f('ix_temp_supplier_orders_import_selected_product_id'), table_name='temp_supplier_orders_import')
    op.drop_index(op.f('ix_temp_supplier_orders_import_imported_by'), table_name='temp_supplier_orders_import')
    op.drop_index(op.f('ix_temp_supplier_orders_import_batch_id'), table_name='temp_supplier_orders_import')
    op.drop_index('ix_temp_so_batch_user', table_name='temp_supplier_orders_import')
    op.drop_table('temp_supplier_orders_import')
    op.drop_index(op.f('ix_temp_stock_import_selected_product_id'), table_name='temp_stock_import')
    op.drop_index(op.f('ix_temp_stock_import_imported_by'), table_name='temp_stock_import')
    op.drop_index(op.f('ix_temp_stock_import_batch_id'), table_name='temp_stock_import')
    op.drop_index('ix_temp_stock_batch_user', table_name='temp_stock_import')
    op.drop_table('temp_stock_import')
    op.drop_index(op.f('ix_temp_price_import_supplier_id'), table_name='temp_price_import')
    op.drop_index(op.f('ix_temp_price_import_selected_product_id'), table_name='temp_price_import')
    op.drop_index(op.f('ix_temp_price_import_imported_by'), table_name='temp_price_import')
    op.drop_index(op.f('ix_temp_price_import_batch_id'), table_name='temp_price_import')
    op.drop_index('ix_temp_price_batch_user', table_name='temp_price_import')
    op.drop_table('temp_price_import')
    op.drop_index(op.f('ix_temp_is_import_selected_product_id'), table_name='temp_is_import')
    op.drop_index(op.f('ix_temp_is_import_imported_by'), table_name='temp_is_import')
    op.drop_index(op.f('ix_temp_is_import_batch_id'), table_name='temp_is_import')
    op.drop_index('ix_temp_is_batch_user', table_name='temp_is_import')
    op.drop_table('temp_is_import')
    op.drop_index(op.f('ix_temp_customer_cost_import_selected_product_id'), table_name='temp_customer_cost_import')
    op.drop_index(op.f('ix_temp_customer_cost_import_imported_by'), table_name='temp_customer_cost_import')
    op.drop_index(op.f('ix_temp_customer_cost_import_batch_id'), table_name='temp_customer_cost_import')
    op.drop_index('ix_temp_cc_import_batch_user', table_name='temp_customer_cost_import')
    op.drop_table('temp_customer_cost_import')
    op.drop_index(op.f('ix_supplier_price_calculations_supplier_id'), table_name='supplier_price_calculations')
    op.drop_index(op.f('ix_supplier_price_calculations_product_id'), table_name='supplier_price_calculations')
    op.drop_index(op.f('ix_supplier_price_calculations_imported_by'), table_name='supplier_price_calculations')
    op.drop_index(op.f('ix_supplier_price_calculations_batch_id'), table_name='supplier_price_calculations')
    op.drop_table('supplier_price_calculations')
    op.drop_table('product_stock')
    op.drop_index(op.f('ix_product_articles_product_id'), table_name='product_articles')
    op.drop_index(op.f('ix_product_articles_name'), table_name='product_articles')
    op.drop_index(op.f('ix_product_articles_article'), table_name='product_articles')
    op.drop_index('ix_prod_articles_article_name', table_name='product_articles')
    op.drop_table('product_articles')
    op.drop_index(op.f('ix_price_history_supplier_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_price_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('current_supplier_prices')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_family'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_pack_types_volume'), table_name='pack_types')
    op.drop_index(op.f('ix_pack_types_name'), table_name='pack_types')
    op.drop_table('pack_types')
    op.drop_table('marking_rates')
    op.drop_table('fixed_costs')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
