"""add temp_product_search_import

Revision ID: dac7ce3d480a
Revises: 72cd2ad40b0c
Create Date: 2026-04-16 01:50:56.316585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac7ce3d480a'
down_revision: Union[str, Sequence[str], None] = '72cd2ad40b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_product_search_import',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('imported_by', sa.String(length=255), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('import_row_no', sa.Integer(), nullable=True),
    sa.Column('source_article', sa.String(length=255), nullable=True),
    sa.Column('source_product_name', sa.String(length=500), nullable=True),
    sa.Column('selected_product_id', sa.Integer(), nullable=True),
    sa.Column('new_product_name', sa.String(length=500), nullable=True),
    sa.Column('new_brand', sa.String(length=255), nullable=True),
    sa.Column('new_pack', sa.Numeric(), nullable=True),
    sa.Column('new_is_excise', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['selected_product_id'], ['products.id'], name=op.f('fk_temp_product_search_import_selected_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_temp_product_search_import'))
    )
    op.create_index('ix_temp_product_search_batch_user', 'temp_product_search_import', ['batch_id', 'imported_by'], unique=False)
    op.create_index(op.f('ix_temp_product_search_import_batch_id'), 'temp_product_search_import', ['batch_id'], unique=False)
    op.create_index(op.f('ix_temp_product_search_import_imported_by'), 'temp_product_search_import', ['imported_by'], unique=False)
    op.create_index(op.f('ix_temp_product_search_import_selected_product_id'), 'temp_product_search_import', ['selected_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_product_search_import_selected_product_id'), table_name='temp_product_search_import')
    op.drop_index(op.f('ix_temp_product_search_import_imported_by'), table_name='temp_product_search_import')
    op.drop_index(op.f('ix_temp_product_search_import_batch_id'), table_name='temp_product_search_import')
    op.drop_index('ix_temp_product_search_batch_user', table_name='temp_product_search_import')
    op.drop_table('temp_product_search_import')
    # ### end Alembic commands ###
