"""order planning

Revision ID: fd5858197539
Revises: 89057fc12abb
Create Date: 2026-05-14 08:32:45.671381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd5858197539'
down_revision: Union[str, Sequence[str], None] = '89057fc12abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_planning_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('avg_sales_month', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_planning_calculations_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_planning_calculations')),
    sa.UniqueConstraint('product_id', 'period_from', 'period_to', name='uq_order_planning_calc_product_period')
    )
    op.create_index('ix_order_planning_calc_period', 'order_planning_calculations', ['period_from', 'period_to'], unique=False)
    op.create_index(op.f('ix_order_planning_calculations_period_from'), 'order_planning_calculations', ['period_from'], unique=False)
    op.create_index(op.f('ix_order_planning_calculations_period_to'), 'order_planning_calculations', ['period_to'], unique=False)
    op.create_index(op.f('ix_order_planning_calculations_product_id'), 'order_planning_calculations', ['product_id'], unique=False)
    op.create_table('sales_product_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sales_code', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sales_article', sa.String(length=255), nullable=True),
    sa.Column('sales_product_name', sa.String(length=500), nullable=True),
    sa.Column('sales_pack', sa.Numeric(), nullable=True),
    sa.Column('sales_brand', sa.String(length=255), nullable=True),
    sa.Column('sales_is_excise', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_product_links_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_product_links'))
    )
    op.create_index('ix_sales_product_links_product_id', 'sales_product_links', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_product_links_sales_code'), 'sales_product_links', ['sales_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_product_links_sales_code'), table_name='sales_product_links')
    op.drop_index('ix_sales_product_links_product_id', table_name='sales_product_links')
    op.drop_table('sales_product_links')
    op.drop_index(op.f('ix_order_planning_calculations_product_id'), table_name='order_planning_calculations')
    op.drop_index(op.f('ix_order_planning_calculations_period_to'), table_name='order_planning_calculations')
    op.drop_index(op.f('ix_order_planning_calculations_period_from'), table_name='order_planning_calculations')
    op.drop_index('ix_order_planning_calc_period', table_name='order_planning_calculations')
    op.drop_table('order_planning_calculations')
    # ### end Alembic commands ###
